# Generated by Django 5.0.4 on 2024-06-09 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('nameOfCopmany', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Descripton', models.TextField(max_length=255)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productModel', models.CharField(max_length=255)),
                ('descripton', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('sizesAndTheirCount', models.JSONField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('Maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lending.companys')),
            ],
        ),
    ]
