# Generated by Django 5.0.4 on 2024-07-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersorders',
            name='orderPositions',
            field=models.CharField(null=True),
        ),
    ]
