# Generated by Django 5.0.4 on 2024-07-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_alter_usersorders_orderpositions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersorders',
            name='orderPositions',
        ),
        migrations.AddField(
            model_name='usersorders',
            name='orderPositions',
            field=models.ManyToManyField(null=True, related_name='products', to='lending.product'),
        ),
    ]
