# Generated by Django 5.0.4 on 2024-07-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_remove_usersorders_orderpositions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersorders',
            name='order_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersorders',
            name='order_phone',
            field=models.CharField(default=11, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersorders',
            name='order_second_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersorders',
            name='order_surname',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersorders',
            name='cart_url',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersorders',
            name='receipt',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersorders',
            name='status',
            field=models.IntegerField(choices=[(0, 'Adopted'), (1, 'Assembled'), (2, 'Sended'), (3, 'Delivered')], default=1),
            preserve_default=False,
        ),
    ]
