# Generated by Django 5.0.4 on 2024-06-10 07:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_rename_adresstoserve_users_adresstoorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='country',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='mail',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersorders',
            name='status',
            field=models.IntegerField(choices=[(0, 'Adopted'), (1, 'Assembled'), (2, 'Sended'), (3, 'Delivered')], null=True),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.IntegerField(null=True)),
                ('receipt', models.ImageField(null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='lending.users')),
            ],
        ),
        migrations.AddField(
            model_name='usersorders',
            name='receipt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='lending.transactions'),
        ),
    ]
