# Generated by Django 5.0.4 on 2024-06-10 13:09

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_rename_uuid_product_id_users_country_users_mail_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('product', django.db.models.manager.Manager()),
            ],
        ),
    ]
