# Generated by Django 5.0.4 on 2024-07-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0006_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizes',
            name='products',
        ),
        migrations.AddField(
            model_name='sizes',
            name='products',
            field=models.ManyToManyField(to='lending.product'),
        ),
    ]
