# Generated by Django 5.0.4 on 2024-06-11 11:24

import lending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0007_alter_product_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='companys',
            name='slug',
            field=models.SlugField(default=lending.models.Companys.get_slug),
        ),
    ]
