# Generated by Django 5.0.4 on 2024-07-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0007_remove_sizes_products_sizes_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='products',
            field=models.ManyToManyField(related_name='sizes', to='lending.product'),
        ),
    ]
