# Generated by Django 5.0.4 on 2024-06-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0007_alter_product_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='companys',
            options={'verbose_name': 'Companys', 'verbose_name_plural': 'Companys'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-cost']},
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='companys',
            old_name='Image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='companys',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companys',
            name='Descripton',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='companys',
            name='nameOfCopmany',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maker', to='lending.companys'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descripton',
            field=models.TextField(default='any description', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='productModel',
            field=models.CharField(max_length=255, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizesAndTheirCount',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(choices=[(1, 'In stock'), (0, 'Out stock')]),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='lending.users'),
        ),
        migrations.AlterField(
            model_name='usersorders',
            name='receipt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userOrders', to='lending.transactions'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='lending.tags'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-cost'], name='lending_pro_cost_d24e52_idx'),
        ),
    ]
