# Generated by Django 5.0.4 on 2024-06-11 11:26

import lending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0008_companys_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companys',
            name='slug',
            field=models.SlugField(blank=True, default=lending.models.Companys.get_slug, unique=True),
        ),
    ]
