# Generated by Django 5.0.4 on 2024-07-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0008_alter_sizes_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizesAndTheirCount',
        ),
        migrations.RemoveField(
            model_name='sizes',
            name='products',
        ),
    ]
