# Generated by Django 5.0.4 on 2024-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0008_tags_alter_companys_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%d/%m/%Y', verbose_name='photo'),
        ),
    ]
