# Generated by Django 5.0.4 on 2024-07-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0009_remove_product_sizesandtheircount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='sizes', to='lending.sizes'),
        ),
    ]
