# Generated by Django 5.0.4 on 2024-07-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0010_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='usersorders',
            name='orderPositions',
        ),
        migrations.AddField(
            model_name='sizes',
            name='products',
            field=models.ManyToManyField(related_name='sizes', to='lending.product'),
        ),
    ]
