# Generated by Django 5.0.4 on 2024-06-12 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0011_alter_companys_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Product', to='lending.companys'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='lending.users'),
        ),
        migrations.AlterField(
            model_name='usersorders',
            name='receipt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userOrders', to='lending.transactions'),
        ),
    ]
