# Generated by Django 5.0.4 on 2024-06-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0012_tags_alter_product_maker_alter_transactions_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='lending.tags'),
        ),
    ]
