# Generated by Django 5.0.4 on 2024-06-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0013_product_tags'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
