# Generated by Django 5.0.4 on 2024-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0014_alter_product_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descripton',
            field=models.TextField(default='any description', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizesAndTheirCount',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
