# Generated by Django 5.0.4 on 2024-06-20 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companys',
            options={'verbose_name': 'Companys', 'verbose_name_plural': 'Companys'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-cost']},
        ),
        migrations.RenameField(
            model_name='companys',
            old_name='Image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='companys',
            name='Descripton',
            field=models.TextField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='companys',
            name='nameOfCopmany',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maker', to='lending.companys'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productModel',
            field=models.CharField(max_length=255, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag', to='lending.tags'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-cost'], name='lending_pro_cost_d24e52_idx'),
        ),
    ]
